export default {
    GET_POKEMONS_LIST_REQUEST:'GET_POKEMONS_LIST_REQUEST',
    GET_POKEMONS_LIST_FAILURE:'GET_POKEMONS_LIST_FAILURE',
    GET_POKEMONS_LIST_SUCCESS:'GET_POKEMONS_LIST_SUCCESS',
    GET_POKEMON_REQUEST:'GET_POKEMON_REQUEST',
    GET_POKEMON_FAILURE:'GET_POKEMON_FAILURE',
    GET_POKEMON_SUCCESS:'GET_POKEMON_SUCCESS',
    RESET_POKEMON:'RESET_POKEMON'
}